[versions]
agp = "8.13.2"
markwon = "4.6.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxCoroutinesPlayServices = "1.10.2"
lifecycleRuntimeKtx = "2.10.0"
lifecycleViewModelCompose = "2.6.1"
activityCompose = "1.12.1"
composeBom = "2025.12.00"
ktorVersion = "3.3.3"
okhttp = "5.3.2"
supabaseKtVersion = "3.2.6"
camera = "1.5.2"
materialIconsCore = "1.7.8"
navigationRuntimeKtx = "2.9.6"
visionInternalVkp = "18.2.3"
animation = "1.10.0"
preferenceKtx = "1.2.1"
playServicesLocation = "21.3.0"
osmdroid = "6.1.20"
material3 = "1.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref="lifecycleViewModelCompose"}
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
supabase-kt-bom = { group = "io.github.jan-tennert.supabase", name = "bom", version.ref = "supabaseKtVersion" }
supabase-kt-postgrest = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt"}
ktor-client = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktorVersion" }
androidx-compose-material-icons = {group = "androidx.compose.material", name = "material-icons-core-android", version.ref = "materialIconsCore"}
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera"}
androidx-camera-compose = { group = "androidx.camera", name = "camera-compose", version.ref = "camera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera" }

vision-internal-vkp = { group = "com.google.mlkit", name = "vision-internal-vkp", version.ref = "visionInternalVkp" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animation" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationRuntimeKtx" }

osmdroid = { group = "org.osmdroid", name = "osmdroid-android", version.ref = "osmdroid" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

